package:
  name: tox
  version: "2.7.0"

source:
  fn: tox-2.7.0.tar.gz
  url: https://pypi.python.org/packages/99/20/2fd208e75c05975bf6436258f469aa233045b93d195cdb442045de0923cc/tox-2.7.0.tar.gz
  md5: 86cced6aa7be700f918eaca41d02ad69
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - py >=1.4.17
    - pluggy >=0.3.0,<1.0

  run:
    - python
    - py >=1.4.17
    - pluggy >=0.3.0,<1.0

test:
  imports:
    - tox

  commands:
    - tox --help

about:
  home: https://tox.readthedocs.org/
  license: MIT
  summary: 'virtualenv-based automation of test activities'
  license_family: MIT
